### ISSUE TITLE
Restructure GIT repostitroy

### ISSUE THREAD

**Issue by AliHasan123** [ahmadtem/Collabo#6]
Rearrage files in the repository for organisational purposes. Delete unused files and make structure it in  a way so that it is easy to navigate through. 
@ahmadtem

**Comment by ahmadtem** [comment]
A new branch _restructured_repo_ was made and all unnecessary files were deleted. The files needed were organized as well and put in folder "Sprint_3". This folder contains the project that should be opened by andrioid studio. Branch _restructured_repo_ was merged into _dev_ and then deleted.
